// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpsp9anf1lph-01ePZi5h53L_yffUK0DI',
    appId: '1:143990812028:web:9599ee7359fd0bc231c8f9',
    messagingSenderId: '143990812028',
    projectId: 'anasinifi-19979',
    authDomain: 'anasinifi-19979.firebaseapp.com',
    storageBucket: 'anasinifi-19979.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAw4OB61fykPi2-xAvEGEMg4G4PDzoRBqM',
    appId: '1:143990812028:android:0095fba04e612c2031c8f9',
    messagingSenderId: '143990812028',
    projectId: 'anasinifi-19979',
    storageBucket: 'anasinifi-19979.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAT8CG_IU3TVXAWaDvfDuwa0s8lhTDe_8',
    appId: '1:143990812028:ios:863d3a18d349df4f31c8f9',
    messagingSenderId: '143990812028',
    projectId: 'anasinifi-19979',
    storageBucket: 'anasinifi-19979.firebasestorage.app',
    iosBundleId: 'com.example.anaSinifi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAT8CG_IU3TVXAWaDvfDuwa0s8lhTDe_8',
    appId: '1:143990812028:ios:863d3a18d349df4f31c8f9',
    messagingSenderId: '143990812028',
    projectId: 'anasinifi-19979',
    storageBucket: 'anasinifi-19979.firebasestorage.app',
    iosBundleId: 'com.example.anaSinifi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpsp9anf1lph-01ePZi5h53L_yffUK0DI',
    appId: '1:143990812028:web:a5976db41eabd77a31c8f9',
    messagingSenderId: '143990812028',
    projectId: 'anasinifi-19979',
    authDomain: 'anasinifi-19979.firebaseapp.com',
    storageBucket: 'anasinifi-19979.firebasestorage.app',
  );
}
